FROM maven:3.6.3-jdk-11

ENV QUARKUS_LAUNCH_DEVMODE=true

COPY pom.xml /workspace/
COPY src /workspace/src/

WORKDIR /workspace/

CMD ["mvn", "compile", "quarkus:dev", "-Dquarkus.live-reload.password=123"]